/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;

/**
 *
 * @author Tuan
 */
public class ManHinhQuanLyThongKeDoanhSoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyPhongJPanel
     */
    public ManHinhQuanLyThongKeDoanhSoJPanel() {
        initComponents();
        addEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpDichVu = new javax.swing.JTabbedPane();
        jpnHoaDon = new javax.swing.JPanel();
        jpnKhachHang = new javax.swing.JPanel();
        jpnDichVu = new javax.swing.JPanel();

        jpnHoaDon.setPreferredSize(new java.awt.Dimension(790, 1000));

        javax.swing.GroupLayout jpnHoaDonLayout = new javax.swing.GroupLayout(jpnHoaDon);
        jpnHoaDon.setLayout(jpnHoaDonLayout);
        jpnHoaDonLayout.setHorizontalGroup(
            jpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jpnHoaDonLayout.setVerticalGroup(
            jpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jtpDichVu.addTab("Thống kê báo cáo hóa đơn", jpnHoaDon);

        jpnKhachHang.setPreferredSize(new java.awt.Dimension(790, 1000));

        javax.swing.GroupLayout jpnKhachHangLayout = new javax.swing.GroupLayout(jpnKhachHang);
        jpnKhachHang.setLayout(jpnKhachHangLayout);
        jpnKhachHangLayout.setHorizontalGroup(
            jpnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jpnKhachHangLayout.setVerticalGroup(
            jpnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jtpDichVu.addTab("Thống kê báo cáo khách hàng", jpnKhachHang);

        jpnDichVu.setPreferredSize(new java.awt.Dimension(790, 1000));

        javax.swing.GroupLayout jpnDichVuLayout = new javax.swing.GroupLayout(jpnDichVu);
        jpnDichVu.setLayout(jpnDichVuLayout);
        jpnDichVuLayout.setHorizontalGroup(
            jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jpnDichVuLayout.setVerticalGroup(
            jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jtpDichVu.addTab("Thống kê báo cáo dịch vụ", jpnDichVu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpDichVu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpDichVu)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpnDichVu;
    private javax.swing.JPanel jpnHoaDon;
    private javax.swing.JPanel jpnKhachHang;
    private javax.swing.JTabbedPane jtpDichVu;
    // End of variables declaration//GEN-END:variables
    private void addEvent(){
        ManHinhQuanLyThongKe_HoaDon thongKeHoaDon =new ManHinhQuanLyThongKe_HoaDon();
        jpnHoaDon.setLayout(new BorderLayout());
        jpnHoaDon.add(thongKeHoaDon,BorderLayout.CENTER);
        
        ManHinhQuanLyThongKe_KhachHang thongKeKhachHang=new ManHinhQuanLyThongKe_KhachHang();
        jpnKhachHang.setLayout(new BorderLayout());
        jpnKhachHang.add(thongKeKhachHang,BorderLayout.CENTER);
        
        ManHinhQuanLyThongKe_DichVu thongKeDichVu =new ManHinhQuanLyThongKe_DichVu();
        jpnDichVu.setLayout(new BorderLayout());
        jpnDichVu.add(thongKeDichVu,BorderLayout.CENTER);
    }
}
