/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bus.TaiKhoanBUS;
import dto.TaiKhoanDTO;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author Tuan
 */
public class ManHinhDangNhapJFrame extends javax.swing.JFrame {

    public static TaiKhoanDTO taiKhoan;
    
    ArrayList<TaiKhoanDTO> listTaiKhoan;
    public ManHinhDangNhapJFrame() {
        initComponents();
        chinhSuaKichThuocIcon("user.png",jlbHinhAnh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnMain = new javax.swing.JPanel();
        jpnTitle = new javax.swing.JPanel();
        jlbTitle = new javax.swing.JLabel();
        jbtDangNhap = new javax.swing.JButton();
        jbtThoat = new javax.swing.JButton();
        jlbHinhAnh = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlbTenDangNhap = new javax.swing.JLabel();
        jlbMatKhau = new javax.swing.JLabel();
        jtfTenDangNhap = new javax.swing.JTextField();
        jpMatKhau = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnTitle.setBackground(new java.awt.Color(255, 51, 51));

        jlbTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlbTitle.setText("LOGIN NOW");

        javax.swing.GroupLayout jpnTitleLayout = new javax.swing.GroupLayout(jpnTitle);
        jpnTitle.setLayout(jpnTitleLayout);
        jpnTitleLayout.setHorizontalGroup(
            jpnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbTitle)
                .addGap(171, 171, 171))
        );
        jpnTitleLayout.setVerticalGroup(
            jpnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTitleLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlbTitle)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jbtDangNhap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N
        jbtDangNhap.setText("Đăng nhập");
        jbtDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDangNhapActionPerformed(evt);
            }
        });

        jbtThoat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        jbtThoat.setText("Hủy");
        jbtThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThoatActionPerformed(evt);
            }
        });

        jlbHinhAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));

        jlbTenDangNhap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbTenDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/username.png"))); // NOI18N
        jlbTenDangNhap.setText("Tên đăng nhập");

        jlbMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/password.png"))); // NOI18N
        jlbMatKhau.setText("Mật khẩu");

        jtfTenDangNhap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jpMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbMatKhau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbTenDangNhap)
                        .addGap(29, 29, 29)
                        .addComponent(jtfTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTenDangNhap)
                    .addComponent(jtfTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMatKhau))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnMainLayout = new javax.swing.GroupLayout(jpnMain);
        jpnMain.setLayout(jpnMainLayout);
        jpnMainLayout.setHorizontalGroup(
            jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtDangNhap)
                        .addGap(44, 44, 44)
                        .addComponent(jbtThoat)
                        .addGap(24, 24, 24)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMainLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jlbHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(113, 113, 113))
        );
        jpnMainLayout.setVerticalGroup(
            jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMainLayout.createSequentialGroup()
                .addComponent(jpnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtThoat)
                    .addComponent(jbtDangNhap))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThoatActionPerformed
        hiddenWindow();
    }//GEN-LAST:event_jbtThoatActionPerformed

    private void jbtDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDangNhapActionPerformed
        if(kiemTraTinhDayDu()){
            xuLyDangNhap();
        }
    }//GEN-LAST:event_jbtDangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtDangNhap;
    private javax.swing.JButton jbtThoat;
    private javax.swing.JLabel jlbHinhAnh;
    private javax.swing.JLabel jlbMatKhau;
    private javax.swing.JLabel jlbTenDangNhap;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JPasswordField jpMatKhau;
    private javax.swing.JPanel jpnMain;
    private javax.swing.JPanel jpnTitle;
    private javax.swing.JTextField jtfTenDangNhap;
    // End of variables declaration//GEN-END:variables

    private void xuLyDangNhap() {
        loadTaiKhoan();
        for (TaiKhoanDTO taiKhoanDTO:listTaiKhoan){ //chạy list tài khoản đã load
            taiKhoan=new TaiKhoanDTO();
            if(jtfTenDangNhap.getText().equals(taiKhoanDTO.getTenDangNhap())){
                if (String.valueOf(jpMatKhau.getPassword()).equals(taiKhoanDTO.getMatKhau())){
                    taiKhoan.setMaTaiKhoan(taiKhoanDTO.getMaTaiKhoan());
                    taiKhoan.setTenDangNhap(taiKhoanDTO.getTenDangNhap());
                    taiKhoan.setMatKhau(taiKhoanDTO.getMatKhau());
                    taiKhoan.setMaNhanVien(taiKhoanDTO.getMaNhanVien());
                    if (taiKhoanDTO.getMaLoaiTaiKhoan()==1){
                        taiKhoan.setMaLoaiTaiKhoan(taiKhoanDTO.getMaLoaiTaiKhoan());
                        ManHinhMainJFrame_GiamDoc giamDoc=new ManHinhMainJFrame_GiamDoc();
                        giamDoc.showWindow();
                        hiddenWindow();
                        break;
                    }
                    else if (taiKhoanDTO.getMaLoaiTaiKhoan()==2){
                        taiKhoan.setMaLoaiTaiKhoan(taiKhoanDTO.getMaLoaiTaiKhoan());
                        ManHinhMainJFrame_LeTan leTan =new ManHinhMainJFrame_LeTan();
                        leTan.showWindow();
                        hiddenWindow();
                        break;
                    }
                    
                }
            }
        }
        if (taiKhoan.getMaLoaiTaiKhoan()<=0){
            JOptionPane.showMessageDialog(null, "Không tìm thấy tài khoản này");
        }
    }
    private void loadTaiKhoan(){
        listTaiKhoan=new ArrayList<>();
        listTaiKhoan=TaiKhoanBUS.layDuLieuTaiKhoan();
        
    }

    public static TaiKhoanDTO getTaiKhoan() {
        return taiKhoan;
    }
    
    private void chinhSuaKichThuocIcon(String name,JLabel lbLabel){
        String input="/image/"+name+"";
        ImageIcon icon=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource(input)));
        Image img =icon.getImage();
        Image imggImage=img.getScaledInstance(lbLabel.getWidth(),lbLabel.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon i=new ImageIcon(imggImage);
        lbLabel.setIcon(i);
    }
    
    public void showWindow(){
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    private void hiddenWindow(){
        this.dispose();
    }

    private boolean kiemTraTinhDayDu() {
       if (jtfTenDangNhap.getText().equals("") && String.valueOf(jpMatKhau.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập tên đăng nhập và mật khẩu");
            return false;
        }
        else if (String.valueOf(jpMatKhau.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mật khẩu");
            return false;
        }
        else if ( jtfTenDangNhap.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập tên đăng nhập");
            return false;
        }
        else{
            return true;
        }
    }
}
