/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bus.HoaDonBus;
import dao.OracleConnection;
import static dao.OracleConnection.conn;
import dto.HoaDon;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Tuan
 */
public class ManHinhQuanLyHoaDonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InhoaDonJPanel
     */
    public static DefaultTableModel dtmHoaDon=new DefaultTableModel();
    public static ArrayList<HoaDon>listHD=null;
    public static HoaDon selectedHD;
    public ManHinhQuanLyHoaDonJPanel() {
        initComponents();
        hienThiDanhSachHoaDon();
    }
    
    public static void hienThiDanhSachHoaDon()
    {
        listHD=new ArrayList<>();
        listHD=HoaDonBus.layDuLieuHoaDon();
        dtmHoaDon=(DefaultTableModel) tbHoaDon.getModel();
        
        for(HoaDon hd : listHD)
        {
            Vector <Object> vt=new Vector<Object>();
            vt.add(hd.getMaHoaDon());
            vt.add(hd.getMaPhong());
            vt.add(hd.getTenKhachHang());
            vt.add(hd.getTienPhong());
            vt.add(hd.getTienDichVu());
            vt.add(hd.getNgayDen());
            vt.add(hd.getNgayDi());
            vt.add(hd.getTenNhanVien());
            vt.add(hd.getTrangThai());
            vt.add(hd.getTongTien());
            vt.add(hd.getTienGiam());
            vt.add(hd.getTienThanhToan());
            dtmHoaDon.addRow(vt);
        }
    }
    
    private void yeuCauHienThiDanhSachHoaDonTimKiem(String tk)
{
    listHD=new ArrayList<>();
    listHD=HoaDonBus.timKiemHoaDon(tk);
    if (listHD.size()<=0){
        JOptionPane.showMessageDialog(null, "Không tìm thấy kết quả");
        return;
    }
    dtmHoaDon=(DefaultTableModel)tbHoaDon.getModel();
    
    
    for(HoaDon hd:listHD)
    {
        Vector<Object> vt=new Vector<Object>();
        vt.add(hd.getMaHoaDon());
            vt.add(hd.getMaPhong());
            vt.add(hd.getTenKhachHang());
            vt.add(hd.getTienPhong());
            vt.add(hd.getTienDichVu());
            vt.add(hd.getNgayDen());
            vt.add(hd.getNgayDi());
            vt.add(hd.getTenNhanVien());
            vt.add(hd.getTrangThai());
            vt.add(hd.getTongTien());
            vt.add(hd.getTienGiam());
            vt.add(hd.getTienThanhToan());
            dtmHoaDon.addRow(vt);
        //tbDichVu.setModel(dtmDichVu);
    }    
}
public static void refreshHoaDon()
{
    dtmHoaDon.setRowCount(0);
    hienThiDanhSachHoaDon();
}

private void refreshHoaDonTimKiem(String tk)
{
    dtmHoaDon.setRowCount(0);
    yeuCauHienThiDanhSachHoaDonTimKiem(tk);
}

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnMain = new javax.swing.JPanel();
        jpnThanhTren = new javax.swing.JPanel();
        jpnTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnTimKiem = new javax.swing.JPanel();
        jtfTimKiem = new javax.swing.JTextField();
        jbtTimKiem = new javax.swing.JButton();
        jpnButton = new javax.swing.JPanel();
        jbtInHoaDon = new javax.swing.JButton();
        jpnTable = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tbHoaDon = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new java.awt.BorderLayout());

        jpnMain.setBackground(new java.awt.Color(153, 153, 255));

        jpnThanhTren.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnThanhTren.setPreferredSize(new java.awt.Dimension(1159, 86));
        jpnThanhTren.setLayout(new javax.swing.BoxLayout(jpnThanhTren, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ HÓA ĐƠN");

        javax.swing.GroupLayout jpnTitleLayout = new javax.swing.GroupLayout(jpnTitle);
        jpnTitle.setLayout(jpnTitleLayout);
        jpnTitleLayout.setHorizontalGroup(
            jpnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jpnTitleLayout.setVerticalGroup(
            jpnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpnThanhTren.add(jpnTitle);

        jtfTimKiem.setBackground(new java.awt.Color(234, 234, 242));
        jtfTimKiem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtfTimKiem.setPreferredSize(new java.awt.Dimension(6, 25));
        jtfTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTimKiemActionPerformed(evt);
            }
        });

        jbtTimKiem.setBackground(new java.awt.Color(0, 204, 204));
        jbtTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TimKiem.png"))); // NOI18N
        jbtTimKiem.setText("Tìm kiếm");
        jbtTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtTimKiemMouseClicked(evt);
            }
        });
        jbtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnTimKiemLayout = new javax.swing.GroupLayout(jpnTimKiem);
        jpnTimKiem.setLayout(jpnTimKiemLayout);
        jpnTimKiemLayout.setHorizontalGroup(
            jpnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTimKiemLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jbtTimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnTimKiemLayout.setVerticalGroup(
            jpnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTimKiemLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jpnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtTimKiem))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jpnThanhTren.add(jpnTimKiem);

        jbtInHoaDon.setBackground(new java.awt.Color(204, 204, 0));
        jbtInHoaDon.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtInHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer.png"))); // NOI18N
        jbtInHoaDon.setText("In hóa đơn");
        jbtInHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtInHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnButtonLayout = new javax.swing.GroupLayout(jpnButton);
        jpnButton.setLayout(jpnButtonLayout);
        jpnButtonLayout.setHorizontalGroup(
            jpnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnButtonLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jbtInHoaDon)
                .addGap(61, 61, 61))
        );
        jpnButtonLayout.setVerticalGroup(
            jpnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnButtonLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jbtInHoaDon)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jpnThanhTren.add(jpnButton);

        jpnTable.setBackground(new java.awt.Color(153, 153, 255));

        tbHoaDon.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tbHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã phòng", "Tên khách hàng", "Tiền phòng", "Tiền dịch vụ", "Ngày đến", "Ngày đi", "Tên nhân viên", "Trạng thái", "Tổng tiền", "Tiền giảm", "Thanh toán"
            }
        ));
        tbHoaDon.setRowHeight(18);
        tbHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHoaDonMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tbHoaDon);

        javax.swing.GroupLayout jpnTableLayout = new javax.swing.GroupLayout(jpnTable);
        jpnTable.setLayout(jpnTableLayout);
        jpnTableLayout.setHorizontalGroup(
            jpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTableLayout.createSequentialGroup()
                .addComponent(jScrollPane9)
                .addGap(0, 0, 0))
        );
        jpnTableLayout.setVerticalGroup(
            jpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnMainLayout = new javax.swing.GroupLayout(jpnMain);
        jpnMain.setLayout(jpnMainLayout);
        jpnMainLayout.setHorizontalGroup(
            jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnThanhTren, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
        );
        jpnMainLayout.setVerticalGroup(
            jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMainLayout.createSequentialGroup()
                .addComponent(jpnThanhTren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jpnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tbHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHoaDonMouseClicked
        // TODO add your handling code here:
        luuThongTinHoaDonKhiClick();
    }//GEN-LAST:event_tbHoaDonMouseClicked

    private void jbtTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtTimKiemMouseClicked
        // TODO add your handling code here:
        String tk=jtfTimKiem.getText();
        if(tk.length()==0)
        {
            refreshHoaDon();
        }
        else
        {
            refreshHoaDonTimKiem(tk);
        }
    }//GEN-LAST:event_jbtTimKiemMouseClicked

    private void jbtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtTimKiemActionPerformed

    private void jtfTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTimKiemActionPerformed

    private void jbtInHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtInHoaDonActionPerformed
        if (selectedHD==null){
            JOptionPane.showMessageDialog(null, "Chọn hóa đơn để in");
        }
        else{
                int check=JOptionPane.showConfirmDialog(null, "Bạn có muốn in hóa đơn", "In hóa đơn", JOptionPane.YES_NO_OPTION);
                if (check==JOptionPane.YES_OPTION){
                    yeuCauXuLyInHoaDon();
                }
        }
    }//GEN-LAST:event_jbtInHoaDonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton jbtInHoaDon;
    private javax.swing.JButton jbtTimKiem;
    private javax.swing.JPanel jpnButton;
    private javax.swing.JPanel jpnMain;
    private javax.swing.JPanel jpnTable;
    private javax.swing.JPanel jpnThanhTren;
    private javax.swing.JPanel jpnTimKiem;
    private javax.swing.JPanel jpnTitle;
    private javax.swing.JTextField jtfTimKiem;
    private static javax.swing.JTable tbHoaDon;
    // End of variables declaration//GEN-END:variables
    
    private void yeuCauXuLyInHoaDon() {
         HoaDonBus.inHoaDon(selectedHD.getMaHoaDon());
 }

    private void luuThongTinHoaDonKhiClick() {
        selectedHD=new HoaDon();
        int selectedRow=tbHoaDon.getSelectedRow();
        if(selectedRow==-1)
            return;
        selectedHD=listHD.get(selectedRow);
    }

    
   
}
