/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;

/**
 *
 * @author Tuan
 */
public class QuanLyPhongJPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyPhongJPanel
     */
    public QuanLyPhongJPanel() {
        initComponents();
        addEvent();
    }

    
    public void addEvent(){
        DanhSachPhong dsPhongJPanel=new DanhSachPhong();
        jpnDanhSachPhong.setLayout(new BorderLayout());
        jpnDanhSachPhong.add(dsPhongJPanel,BorderLayout.CENTER);
        
        ThuePhongJPanel thuePhongJPanel=new ThuePhongJPanel();
        jpnThuePhong.setLayout(new BorderLayout());
        jpnThuePhong.add(thuePhongJPanel,BorderLayout.CENTER);
        
        DatPhongJPanel datPhongJPanel =new DatPhongJPanel();
        jpnDatPhong.setLayout(new BorderLayout());
        jpnDatPhong.add(datPhongJPanel,BorderLayout.CENTER);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpPhong = new javax.swing.JTabbedPane();
        jpnDanhSachPhong = new javax.swing.JPanel();
        jpnThuePhong = new javax.swing.JPanel();
        jpnDatPhong = new javax.swing.JPanel();

        javax.swing.GroupLayout jpnDanhSachPhongLayout = new javax.swing.GroupLayout(jpnDanhSachPhong);
        jpnDanhSachPhong.setLayout(jpnDanhSachPhongLayout);
        jpnDanhSachPhongLayout.setHorizontalGroup(
            jpnDanhSachPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jpnDanhSachPhongLayout.setVerticalGroup(
            jpnDanhSachPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jtpPhong.addTab("Danh sách phòng", jpnDanhSachPhong);

        javax.swing.GroupLayout jpnThuePhongLayout = new javax.swing.GroupLayout(jpnThuePhong);
        jpnThuePhong.setLayout(jpnThuePhongLayout);
        jpnThuePhongLayout.setHorizontalGroup(
            jpnThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jpnThuePhongLayout.setVerticalGroup(
            jpnThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jtpPhong.addTab("Thuê Phòng", jpnThuePhong);

        javax.swing.GroupLayout jpnDatPhongLayout = new javax.swing.GroupLayout(jpnDatPhong);
        jpnDatPhong.setLayout(jpnDatPhongLayout);
        jpnDatPhongLayout.setHorizontalGroup(
            jpnDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jpnDatPhongLayout.setVerticalGroup(
            jpnDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jtpPhong.addTab("Đặt phòng", jpnDatPhong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpPhong)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpPhong)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpnDanhSachPhong;
    private javax.swing.JPanel jpnDatPhong;
    private javax.swing.JPanel jpnThuePhong;
    private javax.swing.JTabbedPane jtpPhong;
    // End of variables declaration//GEN-END:variables
}
