/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ButtonModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import jdk.nashorn.internal.parser.TokenType;
import miniPopup.DanhSachDatPhong;
import miniPopup.HienThiBangDatHoacThuePhongJDialog;
import miniPopup.HienThiBangHuyDatPhong;
import miniPopup.HienThiBangTraPhong;
import miniPopup.NhapThongTinKhachHang;
import model.KhachHang;
import model.PhieuDatPhong;
import model.Phong;
import service.KhachHangService;
import service.PhongService;

/**
 *
 * @author Tuan
 */
public class QuanLyPhongJPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyPhong
     */
    public QuanLyPhongJPanel() {
        initComponents();
        getDuLieuVaoList(); //lấy dữ liệu từ hệ quản trị lên nhưng chưa hiển thị
        addEvents();
        //jRadioButton1.setSelected(true);
    }

    ArrayList<JPanelPhong> arrListJpanelPhong;
    PhongService phongSV;
    ArrayList<Phong> listPhong;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpnThanhTren = new javax.swing.JPanel();
        jbtDanhSachDatPhong = new javax.swing.JButton();
        jlbTimKiem = new javax.swing.JLabel();
        jtfTimKiem = new javax.swing.JTextField();
        jpnButton = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jpnListCacPhong = new javax.swing.JPanel();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jbtDanhSachDatPhong.setText("Danh sách đặt phòng");
        jbtDanhSachDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDanhSachDatPhongActionPerformed(evt);
            }
        });

        jlbTimKiem.setText("Tìm kiếm");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Tất cả phòng");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Phòng trống");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Phòng đã thuê");

        javax.swing.GroupLayout jpnButtonLayout = new javax.swing.GroupLayout(jpnButton);
        jpnButton.setLayout(jpnButtonLayout);
        jpnButtonLayout.setHorizontalGroup(
            jpnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addGap(10, 10, 10)
                .addComponent(jRadioButton3)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpnButtonLayout.setVerticalGroup(
            jpnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnThanhTrenLayout = new javax.swing.GroupLayout(jpnThanhTren);
        jpnThanhTren.setLayout(jpnThanhTrenLayout);
        jpnThanhTrenLayout.setHorizontalGroup(
            jpnThanhTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThanhTrenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jbtDanhSachDatPhong)
                .addGap(57, 57, 57)
                .addComponent(jlbTimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfTimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnThanhTrenLayout.setVerticalGroup(
            jpnThanhTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThanhTrenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnThanhTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtDanhSachDatPhong)
                    .addComponent(jlbTimKiem)
                    .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThanhTrenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpnButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnListCacPhong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        jpnListCacPhong.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnThanhTren, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnListCacPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnThanhTren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnListCacPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorAdded

    private void jbtDanhSachDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDanhSachDatPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtDanhSachDatPhongActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    //Lop de luu tru Jpanel cua phong va ma phong
    private class JPanelPhong extends JPanel{
        String maPhong;
        String maLoaiPhong;
        String trangThai;
        String getMaPhong(){
            return maPhong;
        }
        
        void setMaPhong(String maPhong){
            this.maPhong=maPhong;
        }

        public String getMaLoaiPhong() {
            return maLoaiPhong;
        }

        public void setMaLoaiPhong(String maLoaiPhong) {
            this.maLoaiPhong = maLoaiPhong;
        }

        public String getTrangThai() {
            return trangThai;
        }

        public void setTrangThai(String trangThai) {
            this.trangThai = trangThai;
        }
         
    }
    
    private void getDuLieuVaoList(){
               arrListJpanelPhong=new ArrayList<>();
        phongSV=new PhongService();
        listPhong=phongSV.getDuLieuPhong(); 
        //lay so phong
        JPanelPhong jpnPhong;
        int soPhong=listPhong.size();
        for (int i=0;i<soPhong;i++)
        {
            String phong="Phong "+listPhong.get(i).getMaPhong();
            jpnPhong=new JPanelPhong();
            //Cai dat border
            Border borderPhong= BorderFactory.createLineBorder( Color.RED);
            jpnPhong.setBorder(borderPhong);
            jpnPhong.setPreferredSize(new Dimension(100,100));
            if (listPhong.get(i).getTrangThai().equalsIgnoreCase("K"))
            {
                jpnPhong.setBackground(Color.white);
            }
            else if(listPhong.get(i).getTrangThai().equalsIgnoreCase("C"))
            {
                jpnPhong.setBackground(Color.blue);
            }
            else if (listPhong.get(i).getTrangThai().equalsIgnoreCase("D"))
            {
                jpnPhong.setBackground(Color.yellow);
            }
           // jpnPhong.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
            JLabel lbPhong=new JLabel(phong);
            jpnPhong.add(lbPhong);
           // jpnListCacPhong.add(jpnPhong);
            jpnPhong.setMaPhong(listPhong.get(i).getMaPhong());
            jpnPhong.setMaLoaiPhong(listPhong.get(i).getMaLoaiPhong());
            jpnPhong.setTrangThai(listPhong.get(i).getTrangThai());
            arrListJpanelPhong.add(jpnPhong); //thêm 1 jpanel vào list  
    }
    }
    
    private void hienThiTatCaPhong(){
        
        jpnListCacPhong.removeAll();
        
        jpnListCacPhong.setLayout(new FlowLayout(FlowLayout.LEFT));
        getDuLieuVaoList(); //Phòng trường hợp lúc thêm phòng mới vào thì kích vào tất cả phòng nó không cập nhật
           for (JPanelPhong jpnPhong:arrListJpanelPhong){
               jpnListCacPhong.add(jpnPhong);
           }
          
        jpnListCacPhong.revalidate(); //important
        jpnListCacPhong.repaint(); //important 
        addEventEveryRoom();
    }
    
    private void hienThiPhongTrong(){
        jpnListCacPhong.removeAll();
        getDuLieuVaoList();
        jpnListCacPhong.setLayout(new FlowLayout(FlowLayout.LEFT));
        for (JPanelPhong jpnPhong:arrListJpanelPhong){
            if (jpnPhong.getTrangThai().equalsIgnoreCase("K"))
                jpnListCacPhong.add(jpnPhong);
        }
        jpnListCacPhong.revalidate(); //important
        jpnListCacPhong.repaint(); //important
        addEventEveryRoom();
    }
    
    private void hienThiPhongDaThue(){
        jpnListCacPhong.removeAll();
        getDuLieuVaoList();
        jpnListCacPhong.setLayout(new FlowLayout(FlowLayout.LEFT));
        for (JPanelPhong jpnPhong:arrListJpanelPhong){
            if (jpnPhong.getTrangThai().equalsIgnoreCase("C"))
                jpnListCacPhong.add(jpnPhong,new FlowLayout(FlowLayout.LEFT));
        }
        
                jpnListCacPhong.revalidate(); //important
                jpnListCacPhong.repaint(); //important
                addEventEveryRoom();
    }
    
    private void addEventEveryRoom(){
                Component[] coms = jpnListCacPhong.getComponents();
        for (Component com:coms){ //duyệt tất cả jpanel
            if (com instanceof JPanelPhong){ //chỉ lấy ra các loại JpanelPhong
               JPanelPhong 
                sePhong=(JPanelPhong) com; //giả sự người dùng click vào 1 ô
                sePhong.addMouseListener(new MouseListener() { //tạo sự kiện cho ô này
                   @Override
                   public String toString() {
                       return super.toString(); //To change body of generated methods, choose Tools | Templates.
                   }
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        if(sePhong.trangThai.equalsIgnoreCase("K"))
                        {
                            HienThiBangDatHoacThuePhongJDialog dialog =new HienThiBangDatHoacThuePhongJDialog();
                            
                          dialog.setJlbMaSoPhong(sePhong.maPhong);
                          dialog.setJlbChenMaPhong(sePhong.maPhong);
                          dialog.setJlbChenMaLoaiPhong(sePhong.maLoaiPhong);
                          //khi người dùng click chuột vào button Đặt phòng thì 
                          dialog.getJbtDatPhong().addActionListener(new ActionListener() {
                                @Override
                                public void actionPerformed(ActionEvent e) {
                                    NhapThongTinKhachHang thongTinKHdialog = new NhapThongTinKhachHang();                          
                                    
                                    thongTinKHdialog.getJbtHuy().addActionListener(new ActionListener() {
                                        @Override
                                        public void actionPerformed(ActionEvent e) {
                                            thongTinKHdialog.dispose();
                                           // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                                        }
                                    });
                                    
                                    thongTinKHdialog.getJbtLuu().addActionListener(new ActionListener() {
                                        @Override
                                        public void actionPerformed(ActionEvent e) {
                                            //Lấy thông tin các trường người dùng nhập vào và lưu vào biến kh
                                            KhachHangService khSV=new KhachHangService(); 
                                            
                                   KhachHang kh=new KhachHang();
                                   kh.setMaKH(thongTinKHdialog.getJtfMaKhachHang());
                                   kh.setHoTen(thongTinKHdialog.getJtfHoTen());
                                   kh.setCMND(thongTinKHdialog.getJtfCMND());
                                   kh.setGioiTinh(thongTinKHdialog.getJcbbGioiTinh()); 
                                            try {
                                                kh.setNgaySinh(new SimpleDateFormat("dd/MM/yyyy").parse(thongTinKHdialog.getJtfNgaySinh()));
                                            } catch (ParseException ex) {
                                                Logger.getLogger(QuanLyPhongJPanel.class.getName()).log(Level.SEVERE, null, ex);
                                            }
                                            
                                            //
                                            PhieuDatPhong pdp=new PhieuDatPhong();
                                            pdp.setMaKhachHang(thongTinKHdialog.getJtfMaKhachHang());
                                          //  pdp
                                            //
                                   //Kiểm tra có tồn tại khách hàng chưa
                                   boolean check=khSV.isTonTaiKH(kh.getCMND());
                                   if (check==true){
                                       JOptionPane.showConfirmDialog(null, "Khách hàng này đã tồn tại trong hệ thống. Bạn có muốn tiếp tục đặt phòng với thông tin cũ không?", "Warning", JOptionPane.YES_NO_OPTION);
                                   }
                                   else
                                   {
                                       int flag=khSV.themMoiMotKhachHang(kh);
                                       if (flag!=-1){
                                           JOptionPane.showMessageDialog(null, "Bạn đã đặt phòng thành công! ");
                                       }
                                       else
                                           JOptionPane.showMessageDialog(null, "Đặt phòng không thành công!");
                                   }
                                          
                                            
                                            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                                        }
                                    });
                                   // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                                }
                          });
                        }
                      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        else if (sePhong.trangThai.equalsIgnoreCase("C")){
                            HienThiBangTraPhong bangTraPhong =new HienThiBangTraPhong();
                        }
                        else if (sePhong.trangThai.equalsIgnoreCase("D")){
                            HienThiBangHuyDatPhong bangHuyDatPhong=new HienThiBangHuyDatPhong();
                        }
                    }

                    @Override
                    public void mousePressed(MouseEvent e) {
                      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {
                      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                    }
                });
            }
        }
    }
    
    private void addEvents(){
        /*****************/

        
        
                jRadioButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               
                hienThiTatCaPhong();
              //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
                
        jRadioButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                hienThiPhongTrong();
             //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
        jRadioButton3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                hienThiPhongDaThue();
               // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
        jbtDanhSachDatPhong.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    DanhSachDatPhong dsdp=new DanhSachDatPhong();
                    
                   // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
            });
    }
      /*********************/
  
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JButton jbtDanhSachDatPhong;
    private javax.swing.JLabel jlbTimKiem;
    private javax.swing.JPanel jpnButton;
    private javax.swing.JPanel jpnListCacPhong;
    private javax.swing.JPanel jpnThanhTren;
    private javax.swing.JTextField jtfTimKiem;
    // End of variables declaration//GEN-END:variables
}
