/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.miniPop;

import bus.LoaiTaiKhoanBUS;
import bus.TaiKhoanBUS;
import dto.LoaiTaiKhoanDTO;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Tuan
 */
public class FormTaoTaiKhoanChoNhanVienJDialog extends javax.swing.JDialog {

    /**
     * Creates new form FormTaoTaiKhoanChoNhanVienJDialog
     */
    public FormTaoTaiKhoanChoNhanVienJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    JTextField jtfCMND;
    ArrayList<LoaiTaiKhoanDTO> listLoaiTK;
    public FormTaoTaiKhoanChoNhanVienJDialog(JTextField jtfCMND){
        initComponents();
        hienThiLoaiTaiKhoan();
        setVisible(true);
        setLocationRelativeTo(null);
         this.jtfCMND=jtfCMND;
        ganDuLieuMacDinh();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfTen = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jcbbLoaiTaiKhoan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jpNhapLaiMK = new javax.swing.JPasswordField();
        jpMatKhau = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Tên tài khoản");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Mật khẩu");

        jtfTen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        jButton1.setText("Lưu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Huy.png"))); // NOI18N
        jButton2.setText("Hủy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Loại tài khoản");

        jcbbLoaiTaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Gõ lại mật khẩu");

        jpNhapLaiMK.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jpMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfTen, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(jcbbLoaiTaiKhoan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpNhapLaiMK)
                            .addComponent(jpMatKhau))
                        .addGap(57, 57, 57))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jpMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jpNhapLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbbLoaiTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(39, 39, 39))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        yeuCauTaoTaiKhoan();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<LoaiTaiKhoanDTO> jcbbLoaiTaiKhoan;
    private javax.swing.JPasswordField jpMatKhau;
    private javax.swing.JPasswordField jpNhapLaiMK;
    private javax.swing.JTextField jtfTen;
    // End of variables declaration//GEN-END:variables
    private void hienThiLoaiTaiKhoan(){
        listLoaiTK=LoaiTaiKhoanBUS.layDanhSachLoaiTaiKhoan();
        for (LoaiTaiKhoanDTO taiKhoan:listLoaiTK){
            jcbbLoaiTaiKhoan.addItem(taiKhoan);
        }
        jcbbLoaiTaiKhoan.setSelectedIndex(1);
    }
    
    private void ganDuLieuMacDinh(){
        String user="user"+jtfCMND.getText();
        jtfTen.setText(user);
        jpMatKhau.setText("123456");
        jpNhapLaiMK.setText("123456");
    }
    
    private boolean kiemTraTinhDayDuTruong(){
        if(jtfTen.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Tên đăng nhập trống");
            return false;
        }
        else if(jpMatKhau.getPassword().equals("")){
            JOptionPane.showMessageDialog(null, "Mật khẩu trống");
            return false;
        }
        else if(jpNhapLaiMK.getPassword().equals("")){
            JOptionPane.showMessageDialog(null, "Nhập lại mật khẩu");
            return false;
        }
        return true;
    }
    
    private boolean kiemTraMatKhauHopLe(){
        if (String.valueOf(jpMatKhau.getPassword()).equals(String.valueOf(jpNhapLaiMK.getPassword()))==false){
            JOptionPane.showMessageDialog(null, "Mật khẩu không khớp");
            return false;
        }
        return true;
    }

    private void yeuCauTaoTaiKhoan() {
        if(kiemTraTinhDayDuTruong() && kiemTraMatKhauHopLe())
        {
            boolean check=TaiKhoanBUS.taoTaiKhoanNhanVien(Integer.parseInt(jtfCMND.getText()), ((LoaiTaiKhoanDTO)jcbbLoaiTaiKhoan.getSelectedItem()).getMaLoaiTaiKhoan(),
                    jtfTen.getText(),String.valueOf(jpMatKhau.getPassword()));
            if(check){
                JOptionPane.showMessageDialog(null, "Tạo tài khoản thành công");
                dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Tạo tài khoản thất bại");
            }
        }
    }
    
}
