/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.miniPop;

import bus.NhanVienBus;
import bus.TaiKhoanBUS;
import dto.NhanVienDTO;
import gui.ManHinhQuanLyNhanVienJPanel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author COMPUTER
 */
public class FormSuaNhanVienJDialog extends javax.swing.JDialog {

    /**
     * Creates new form SuaNhanVienJDialog
     */
    DefaultTableModel dtm;
    JTable jtable;
    NhanVienDTO nv; 
    NhanVienDTO newInfoNhanVien; //lưu trữ dữ liệu mới của người dùng nhập vào
    //ArrayList<NhanVienDTO> listNV;
    ArrayList<NhanVienDTO> listNguoiQuanLy;
    
    public FormSuaNhanVienJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public FormSuaNhanVienJDialog(ArrayList<NhanVienDTO> listNV, DefaultTableModel dtm,JTable jtable,NhanVienDTO nv ) throws SQLException {            
        initComponents();
        this.dtm=dtm;
        this.jtable=jtable;
        this.nv=nv;
       // this.listNV=listNV;
        hienThiDanhSachNguoiQuanLy();
        chuyenDuLieuLenForm();
        setVisible(true);
        setLocationRelativeTo(null);
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtfSoDT = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jtfCMND = new javax.swing.JTextField();
        jtfHoVaten = new javax.swing.JTextField();
        jtfMaNhanVien = new javax.swing.JTextField();
        jcNgaySinh = new com.toedter.calendar.JDateChooser();
        jcNgayVaoLam = new com.toedter.calendar.JDateChooser();
        jcbbNguoiQuanLy = new javax.swing.JComboBox<>();
        jcbbGioiTinh = new javax.swing.JComboBox();
        jtfDiaChi = new javax.swing.JTextField();
        jcbbTrangThai = new javax.swing.JComboBox();
        jbtLuu = new javax.swing.JButton();
        jbtHuy = new javax.swing.JButton();
        jbtTaoTaiKhoan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nhân viên");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Mã nhân viên");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Họ tên");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Ngày sinh");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Ngày vào làm");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("CMND");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Người quản lý");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Số điện thoại");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Email");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Giới tính");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Địa chỉ");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Trạng thái");

        jtfSoDT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtfEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtfCMND.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtfHoVaten.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtfMaNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfMaNhanVien.setEnabled(false);

        jcNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jcNgayVaoLam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jcbbNguoiQuanLy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbbNguoiQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbNguoiQuanLyActionPerformed(evt);
            }
        });

        jcbbGioiTinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jcbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));

        jtfDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jcbbTrangThai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jcbbTrangThai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Đang làm", "Đã nghỉ" }));

        jbtLuu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        jbtLuu.setText("Lưu");
        jbtLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtLuuMouseClicked(evt);
            }
        });
        jbtLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLuuActionPerformed(evt);
            }
        });

        jbtHuy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Huy.png"))); // NOI18N
        jbtHuy.setText("Hủy");
        jbtHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtHuyMouseClicked(evt);
            }
        });
        jbtHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtHuyActionPerformed(evt);
            }
        });

        jbtTaoTaiKhoan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtTaoTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/account.png"))); // NOI18N
        jbtTaoTaiKhoan.setText("Tạo tài khoản");
        jbtTaoTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtTaoTaiKhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfHoVaten, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                .addComponent(jtfMaNhanVien))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jcNgayVaoLam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(jcNgaySinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfCMND, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jcbbNguoiQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtfSoDT, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                        .addComponent(jtfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                        .addComponent(jcbbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfDiaChi))
                                    .addComponent(jcbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jbtTaoTaiKhoan)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jbtHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfHoVaten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jcbbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbbNguoiQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtTaoTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtLuuMouseClicked
        
    }//GEN-LAST:event_jbtLuuMouseClicked

    private void jbtHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtHuyMouseClicked
      
    }//GEN-LAST:event_jbtHuyMouseClicked

    private void jbtLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLuuActionPerformed
       yeuCauCapNhatThongTinNhanVien();
    }//GEN-LAST:event_jbtLuuActionPerformed

    private void jbtHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtHuyActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbtHuyActionPerformed

    private void jcbbNguoiQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbNguoiQuanLyActionPerformed
        
    }//GEN-LAST:event_jcbbNguoiQuanLyActionPerformed

    private void jbtTaoTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtTaoTaiKhoanActionPerformed
        if(kiemTraTruongDuLieuNhapVao())
        yeuCauHienThiFormTaoTaiKhoan();
    }//GEN-LAST:event_jbtTaoTaiKhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtHuy;
    private javax.swing.JButton jbtLuu;
    private javax.swing.JButton jbtTaoTaiKhoan;
    private com.toedter.calendar.JDateChooser jcNgaySinh;
    private com.toedter.calendar.JDateChooser jcNgayVaoLam;
    private javax.swing.JComboBox jcbbGioiTinh;
    private javax.swing.JComboBox<NhanVienDTO> jcbbNguoiQuanLy;
    private javax.swing.JComboBox jcbbTrangThai;
    private javax.swing.JTextField jtfCMND;
    private javax.swing.JTextField jtfDiaChi;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfHoVaten;
    private javax.swing.JTextField jtfMaNhanVien;
    private javax.swing.JTextField jtfSoDT;
    // End of variables declaration//GEN-END:variables
    
    private void yeuCauHienThiFormTaoTaiKhoan() {
        FormTaoTaiKhoanChoNhanVienJDialog form=new FormTaoTaiKhoanChoNhanVienJDialog(jtfCMND);
    }

    private void yeuCauCapNhatThongTinNhanVien() {
        boolean checkInput=kiemTraTruongDuLieuNhapVao();
        if (checkInput){
            luuThongTinMoiCuaNhanVien();
            int check=NhanVienBus.capNhatThongTinNhanVien(newInfoNhanVien);
            if(check==1){
                JOptionPane.showMessageDialog(null, "Cập nhật thành công");
                try {
                    lamMoiDuLieu();
                } catch (SQLException ex) {
                    Logger.getLogger(FormSuaNhanVienJDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
                dispose();
            }
            else {
                JOptionPane.showMessageDialog(null, "Cập nhật thất bại");
            }
        }
    }
    
        public void showWindows(){
       // this.setSize(400,500);
       this.setLocationRelativeTo(null);
       this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       this.setVisible(true);        
    }
    
    private void lamMoiDuLieu() throws SQLException{
         ManHinhQuanLyNhanVienJPanel.lamMoiDuLieu();
    }
    
    private boolean kiemTraTruongDuLieuNhapVao()
    {
         if (jtfHoVaten.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Họ và tên không được để trống!");
            return false;
        }
        else if (jcNgaySinh.getDate()==null){
            JOptionPane.showMessageDialog(null, "Ngày sinh không được để trống");
            return false;
        }
        else if (jcNgayVaoLam.getDate()==null){
            JOptionPane.showMessageDialog(null, "Ngày vào làm không được để trống");
            return false;
        }
        else if (jtfCMND.getText().equals("")){
            JOptionPane.showMessageDialog(null, "CMND không được để trống");
            return false;
        }
        else if (jtfDiaChi.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Địa chỉ không được để trống");
            return false;
        }
        else if (jtfSoDT.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Số điện thoại không được để trống");
            return false;
        }
        return true;
    }
    
    private void hienThiDanhSachNguoiQuanLy() throws SQLException{
        listNguoiQuanLy=new ArrayList<>();
        listNguoiQuanLy=NhanVienBus.layDuLieuNhanVien();
        NhanVienDTO defaultSelection=new NhanVienDTO();
        defaultSelection.setHoTen("Mặc định");  
        jcbbNguoiQuanLy.addItem(defaultSelection);
        for (NhanVienDTO nv:listNguoiQuanLy){
            jcbbNguoiQuanLy.addItem(nv);
        }      
    }

    private void chuyenDuLieuLenForm(){
        jtfMaNhanVien.setText(Integer.toString(nv.getMaNhanVien())); //chuyển số về chuỗi
        jtfHoVaten.setText(nv.getHoTen());
        jcNgaySinh.setDate(nv.getNgaySinh());
        jcNgayVaoLam.setDate(nv.getNgayVaoLam());
        jtfCMND.setText(Integer.toString(nv.getCMND()));
        jcbbGioiTinh.setSelectedItem(nv.getGioiTinh());
        jtfDiaChi.setText(nv.getDiaChi());
        jtfEmail.setText(nv.getEmail());
        jtfSoDT.setText(nv.getSoDT());
        jcbbTrangThai.setSelectedItem(nv.getTrangThai());
        
        boolean flag=false;
        for (int i=1;i<listNguoiQuanLy.size();i++){
            if (nv.getMaNguoiQuanLy()==listNguoiQuanLy.get(i).getMaNhanVien()){
                jcbbNguoiQuanLy.setSelectedIndex(i+1);
                flag=true;
            }
        }
        
        if(flag==false){
            jcbbNguoiQuanLy.setSelectedIndex(0);
        }
    }
    
    private void luuThongTinMoiCuaNhanVien() {
        newInfoNhanVien=new NhanVienDTO("");
        {
        try{ 
            newInfoNhanVien.setCMND(Integer.parseInt(jtfCMND.getText()));
           }
        catch(NumberFormatException nfe)
        {
            JOptionPane.showMessageDialog(null,"CMND không hợp lệ");
            return;
        }        
    
        newInfoNhanVien.setMaNhanVien(Integer.parseInt(jtfMaNhanVien.getText()));
        newInfoNhanVien.setHoTen(jtfHoVaten.getText());
        newInfoNhanVien.setDiaChi(jtfDiaChi.getText());
        newInfoNhanVien.setGioiTinh(jcbbGioiTinh.getSelectedItem().toString());
        newInfoNhanVien.setNgaySinh(jcNgaySinh.getDate());
        newInfoNhanVien.setNgayVaoLam(jcNgayVaoLam.getDate());
        newInfoNhanVien.setTrangThai(jcbbTrangThai.getSelectedItem().toString());
        newInfoNhanVien.setEmail(jtfEmail.getText());
        newInfoNhanVien.setSoDT(jtfSoDT.getText());
        newInfoNhanVien.setMaNguoiQuanLy(((NhanVienDTO)jcbbNguoiQuanLy.getSelectedItem()).getMaNhanVien());
    }
    }
}
