/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.miniPop;

import bus.PhieuDatPhongBUS;
import dto.PhieuDatPhongDTO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import newClass.JPanelPhong;

/**
 *
 * @author Tuan
 */
public class HienThiFormThongTinDatPhong_PhongJPanel extends javax.swing.JPanel {

    JPanelPhong selecJPanelPhong;
    ArrayList <PhieuDatPhongDTO> listDatPhong;
    DefaultTableModel dtmPhieuDatPhong;
    public HienThiFormThongTinDatPhong_PhongJPanel(JPanelPhong selectedJPanelPhong) {
        setVisible(true);
        initComponents();
        this.selecJPanelPhong=selectedJPanelPhong;       
        chuyenDuLieuLenForm();
    }

    private void chuyenDuLieuLenForm(){
        dtmPhieuDatPhong=new DefaultTableModel();
        listDatPhong= new ArrayList<>();
        listDatPhong=PhieuDatPhongBUS.getThongTinDatPhongCuThe1Phong(selecJPanelPhong.getMaPhong());
        dtmPhieuDatPhong=(DefaultTableModel) jtbPhieuDatPhong.getModel();
        for (PhieuDatPhongDTO datPhongDTO:listDatPhong){
            Vector<Object> vec=new Vector<Object>();
            vec.add(datPhongDTO.getTenKH());
            vec.add(datPhongDTO.getTenNV());
            vec.add(datPhongDTO.getNgayDat());
            vec.add(datPhongDTO.getNgayDen());
            vec.add(datPhongDTO.getNgayDi());
            dtmPhieuDatPhong.addRow(vec);
        }
        jtbPhieuDatPhong.setModel(dtmPhieuDatPhong);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbPhieuDatPhong = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin đặt phòng"));
        jPanel1.setToolTipText("");

        jtbPhieuDatPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên khách hàng", "Tên nhân viên", "Ngày đặt", "Ngày đến", "Ngày đi"
            }
        ));
        jScrollPane1.setViewportView(jtbPhieuDatPhong);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbPhieuDatPhong;
    // End of variables declaration//GEN-END:variables
}
